// Generated 16-feb-2022 12:32:36 by Hibernate Tools 4.3.1
package entities;

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Equipos generated by hbm2java
 */
@Entity
@Table(name = "equipos", catalog = "nba")
public class Equipos implements java.io.Serializable {

    private String nombre;
    private String ciudad;
    private String conferencia;
    private String division;
    private Set<Jugadores> jugadoreses = new HashSet<Jugadores>(0);

    public Equipos() {
    }

    public Equipos(String nombre) {
        this.nombre = nombre;
    }

    public Equipos(String nombre, String ciudad, String conferencia, String division, Set<Jugadores> jugadoreses) {
        this.nombre = nombre;
        this.ciudad = ciudad;
        this.conferencia = conferencia;
        this.division = division;
        this.jugadoreses = jugadoreses;
    }

    @Id

    @Column(name = "nombre", unique = true, nullable = false, length = 20)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "ciudad", length = 20)
    public String getCiudad() {
        return this.ciudad;
    }

    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }

    @Column(name = "conferencia", length = 4)
    public String getConferencia() {
        return this.conferencia;
    }

    public void setConferencia(String conferencia) {
        this.conferencia = conferencia;
    }

    @Column(name = "division", length = 9)
    public String getDivision() {
        return this.division;
    }

    public void setDivision(String division) {
        this.division = division;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "equipos")
    public Set<Jugadores> getJugadoreses() {
        return this.jugadoreses;
    }

    public void setJugadoreses(Set<Jugadores> jugadoreses) {
        this.jugadoreses = jugadoreses;
    }

}
