// Generated 16-feb-2022 12:32:36 by Hibernate Tools 4.3.1

package entities;

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
/**
 * Jugadores generated by hbm2java
 */
@Entity
@Table(name="jugadores"
    ,catalog="nba"
)
public class Jugadores  implements java.io.Serializable {


     private int codigo;
     private Equipos equipos;
     private String nombre;
     private String procedencia;
     private String altura;
     private Integer peso;
     private String posicion;
     private Set<Estadisticas> estadisticases = new HashSet<Estadisticas>(0);

    public Jugadores() {
    }

	
    public Jugadores(int codigo) {
        this.codigo = codigo;
    }
    public Jugadores(int codigo, Equipos equipos, String nombre, String procedencia, String altura, Integer peso, String posicion, Set<Estadisticas> estadisticases) {
       this.codigo = codigo;
       this.equipos = equipos;
       this.nombre = nombre;
       this.procedencia = procedencia;
       this.altura = altura;
       this.peso = peso;
       this.posicion = posicion;
       this.estadisticases = estadisticases;
    }
   
     @Id 

    
    @Column(name="codigo", unique=true, nullable=false)
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="nombre_equipo")
    public Equipos getEquipos() {
        return this.equipos;
    }
    
    public void setEquipos(Equipos equipos) {
        this.equipos = equipos;
    }

    
    @Column(name="nombre", length=30)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="procedencia", length=20)
    public String getProcedencia() {
        return this.procedencia;
    }
    
    public void setProcedencia(String procedencia) {
        this.procedencia = procedencia;
    }

    
    @Column(name="altura", length=4)
    public String getAltura() {
        return this.altura;
    }
    
    public void setAltura(String altura) {
        this.altura = altura;
    }

    
    @Column(name="peso")
    public Integer getPeso() {
        return this.peso;
    }
    
    public void setPeso(Integer peso) {
        this.peso = peso;
    }

    
    @Column(name="posicion", length=5)
    public String getPosicion() {
        return this.posicion;
    }
    
    public void setPosicion(String posicion) {
        this.posicion = posicion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="jugadores")
    public Set<Estadisticas> getEstadisticases() {
        return this.estadisticases;
    }
    
    public void setEstadisticases(Set<Estadisticas> estadisticases) {
        this.estadisticases = estadisticases;
    }




}


